/** @type {import('prettier').Config & import('prettier-plugin-tailwindcss').options} */
const config = {
  trailingComma: 'es5',
  tabWidth: 2,
  semi: false,
  singleQuote: true,
  arrowParens: 'always',
  printWidth: 100,
  plugins: ['prettier-plugin-tailwindcss', '@trivago/prettier-plugin-sort-imports'],
  importOrder: [
    '@/styles/styles.css',
    '-polyfill$',
    '^vue$',
    '^@apollo/client',
    '<THIRD_PARTY_MODULES>',
    '^@/types/(.*)$',
    '^@/context/(.*)$',
    '^@/stores/(.*)$',
    '^@/classes/(.*)$',
    '^@/hooks/(.*)$',
    '^@/components/atoms/(.*)$',
    '^@/components/molecules/(.*)$',
    '^@/components/organisms/(.*)$',
    '^@/components/layouts/(.*)$',
    '^@/components/pages/(.*)$',
    '^@/components/(.*)$',
    '^@(.*)$',
    '^@/services/(.*)$',
    '^@/utils/(.*)$',
    '^@/constants/(.*)$',
    '^@/common/(.*)$',
    '^(../)',
    '^(./)(?!styles.module)',
    '.scss$',
    '.css$',
    './styles.module.scss',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
}

export default config
